version: 2
multi-ecosystem-groups:
  weekly-updates:
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 1
    commit-message:
      prefix: "chore"
      include: "scope"
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    patterns:
      - "*"
    multi-ecosystem-group: "weekly-updates"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    patterns:
      - "*"
    multi-ecosystem-group: "weekly-updates"
